# Site settings
title: Electronut Labs

#url:              http://localhost:4000
url:              http://electronut.in

email: info@electronut.in
description: > # this means to ignore newlines until "baseurl:"
  A small business focused on creating unique, useful electronics hardware and
  educational content for Makers worldwide
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: electronutLabs
github_username:  electronut

# Build settings
markdown: kramdown

permalink:   /:title/
gems: [jekyll-paginate]

#paginate: 4
#paginate_path: "blog/page:num"
