# Site wide configuration

title:            electronut.in
locale:           en_US
url:              http://localhost:4000
#url:              http://electronut.in

# Jekyll configuration

permalink:   /:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Mahesh Venkitachalam
  avatar: portrait.jpg
  bio: "Programmer/Electronics Hacker/Photographer/Writer from Bangalore."
  email: info@electronut.in
  disqus-shortname: electronutin
  twitter: electronutIN
  github: electronut
  flickr: tat-tvam-asi
  facebook: #username
  google:
    plus: #username
    analytics: UA-44220663-2
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
